#ship_types
Ship_types=
[
"HFO_oiltanker"
"LNG_oiltanker"
"LSFO_oiltanker"
"Methanol_oiltanker"
"Biodiesel_oiltanker"
"Ammonia_oiltanker"
"Electricity_oiltanker"
"Liquified methane_oiltanker"
"Hydrogen_oiltanker"
"HFO_bulkcarrier"
"LNG_bulkcarrier"
"LSFO_bulkcarrier"
"Methanol_bulkcarrier"
"Biodiesel_bulkcarrier"
"Ammonia_bulkcarrier"
"Electricity_bulkcarrier"
"Liquified methane_bulkcarrier"
"Hydrogen_bulkcarrier"
"HFO_generalcargo"
"LNG_generalcargo"
"LSFO_generalcargo"
"Methanol_generalcargo"
"Biodiesel_generalcargo"
"Ammonia_generalcargo"
"Electricity_generalcargo"
"Liquified methane_generalcargo"
"Hydrogen_generalcargo"
"HFO_containership"
"LNG_containership"
"LSFO_containership"
"Methanol_containership"
"Biodiesel_containership"
"Ammonia_containership"
"Electricity_containership"
"Liquified methane_containership"
"Hydrogen_containership"
"HFO_other"
"LNG_other"
"LSFO_other"
"Methanol_other"
"Biodiesel_other"
"Ammonia_other"
"Electricity_other"
"Liquified methane_other"
"Hydrogen_other"
]
